name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Show eligible build destinations
      run: cd Handbook; xcodebuild -showdestinations -scheme Handbook-Package
    - name: Build and test ( iOS 15.2)
      run: cd Handbook; xcodebuild test -scheme Earendil -destination 'platform=iOS Simulator,OS=15.2,name=iPhone 11'
