name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Show eligible build destinations
      run: cd Handbook; xcodebuild -showdestinations -scheme Handbook-Package
    - name: Build
      run: cd Handbook; swift build -v
    - name: Run tests
      run: cd Handbook; swift test -v
